# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Approved'), (0, 'Pending')], null=True),
        ),
    ]
