# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180925_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_num',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
